# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# exclusions should be separated with a pipe (|) character and a newline
exclude: |
  (?x)^(
      test/expected/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: '.+/tsconfig.json'
      - id: check-shebang-scripts-are-executable
        exclude: '.+\.rs' # would be triggered by #![some_attribute]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: trailing-whitespace
    rev: v5.0.0

  - repo: https://github.com/pre-commit/mirrors-clang-format
    hooks:
      - id: clang-format
        types: [ c++ ]
    rev: v19.1.4

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    hooks:
      - id: actionlint
        additional_dependencies: [ shellcheck-py ]
    rev: v1.7.4.20

  - repo: local
    hooks:
      - id: cargo-fmt
        description: "Automatically format Rust code with cargo fmt"
        entry: sh -c "cd rust && cargo fmt --all"
        language: rust
        name: Rust Format
        pass_filenames: false
