# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# exclusions should be separated with a pipe (|) character and a newline
exclude: |
  (?x)^(
      test/expected/.*
      |java/gradlew(\.bat)?
  )$

ci:
  autoupdate_schedule: monthly
  # sometimes fails https://github.com/keith/pre-commit-buildifier/issues/13
  skip: [ buildifier ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: '.+/tsconfig.json'
      - id: check-shebang-scripts-are-executable
        exclude: '.+\.rs' # would be triggered by #![some_attribute]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [ --allow-multiple-documents ]
        exclude: mkdocs/mkdocs.yml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        types: [ c++ ]
        args: ["-style=file:.clang-format"]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.8.24
    hooks:
      - id: actionlint
        additional_dependencies: [ shellcheck-py ]
        exclude: '\.github/workflows/rust(-legacy)?\.yml'

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust Format
        description: "Automatically format Rust code with cargo fmt"
        entry: sh -c "cd rust && cargo fmt --all"
        language: rust
        pass_filenames: false

  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1
    hooks:
      - id: buildifier
