site_name: MapLibre Tile Specification
site_url: https://www.maplibre.org/maplibre-tile-spec
repo_url: https://github.com/maplibre/maplibre-tile-spec
site_description: MapLibre Tile Specification
edit_uri: edit/main/docs
extra_css:
  - assets/extra.css
theme:
  name: 'material'
  favicon: https://maplibre.org/favicon.ico
  logo: assets/logo.svg
  features:
    - content.code.copy
    - search.suggest
    - navigation.instant
    - navigation.sections
    - content.action.edit
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
      check_paths: true
      base_path: docs/snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      permalink_title: "Link to this section"
      baselevel: 1
      toc_depth: 6
nav:
  - Home: index.md
  - Implementation Status: implementation-status.md
  - Encoding Algorithms: encodings.md
  - Specification: specification.md
  - Geometry Spec: geometry.md

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@maplibre
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/maplibre
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/maplibre
    - icon: fontawesome/brands/slack
      link: https://osmus.slack.com/archives/C01G3D28DAB
    - icon: fontawesome/brands/github
      link: https://github.com/maplibre
plugins:
  - search
  - callouts
  - social:
      cards_layout_options:
        background_color: '#295DAA'
  - panzoom
  - add-number:
      excludes: ['*']
      includes:
        - specification.md
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
