[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = true
git_release_name = "rust-{{ package }}-v{{ version }}"
git_release_body = """
{{ changelog }}
{% if remote.contributors %}

### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""
git_tag_enable = true
git_tag_name = "rust-{{ package }}-v{{ version }}"
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore(rust): release{% if package %} {{ package }}{% endif %}{% if version %} v{{ version }}{% endif %}"
publish_allow_dirty = false
publish_no_verify = true # we have already thoroughly verified that all aspects of our project work in CI before this step
semver_check = true
publish_timeout = "10m" # set a timeout for `cargo publish`
publish = true

[[package]]
name = "mlt"

[[package]]
name = "mlt-core"

[[package]]
name = "mlt-py"
git_tag_name = "python-mlt-v{{ version }}"
git_release_name = "python-mlt-v{{ version }}"

[[package]]
name = "mlt-synthetics"
publish = false

[changelog]
# always include commits with breaking changes in the changelog
protect_breaking_commits = true
