[package]
name = "mlt-core"
description = "MapLibre Tile library code"
version = "0.1.0"
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
borrowme = "0.0.15"
fastpfor = "0.6"
geo-types = "0.7.18"
hex = "0.4.3"
integer-encoding = "4.0.2"
mvt-reader = "2.2.0"
num-traits = "0.2.19"
num_enum = "0.7.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
strum = { version = "0.27.0", default-features = false, features = ["derive"] }
thiserror = "2.0.11"
zigzag = "0.1.0"

[dev-dependencies]
insta = "1.43.2"
json5 = "1.3"
pretty_assertions = "1.4"
rstest = "0.26.1"
test_each_file = "0.3.5"

[lints.rust]
unsafe_code = "forbid"
unused_qualifications = "warn"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

# Restrictions
panic_in_result_fn = "warn"
todo = "warn"
unused_trait_names = "warn"
unimplemented = "warn"

# Too noisy
missing_errors_doc = "allow"
multiple_crate_versions = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
