[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = true
git_tag_enable = true
git_tag_name = "rust-{{ package }}-v{{ version }}"
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore(rust): release{% if package %} {{ package }}{% endif %}{% if version %}  v{{ version }}{% endif %}"
publish_allow_dirty = false
publish_no_verify = true # we have already thoroughly verified that all aspects of our project work in CI before this step
semver_check = true
publish_timeout = "10m" # set a timeout for `cargo publish`

[[package]]
name = "mlt"
publish = true

[[package]]
name = "mlt-core"
publish = true

[[package]]
name = "mlt-pyo3"
publish = true

[[package]]
name = "mlt-synthetics"
publish = false

[changelog]
# always include commits with breaking changes in the changelog
protect_breaking_commits = true
