table_order = [
    'workspace',
    'package',
    'lib',
    'bin',
    'example',
    'bench',
    'features',
    'dependencies',
    'build-dependencies',
    'dev-dependencies',
    'profile',
    'lints',
]
