[versions]
tileverse = "1.1.0"
junit-jupiter = "6.0.2"

[libraries]
commons-cli = { group = "commons-cli", name = "commons-cli", version = "1.11.0"}
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.28.0" }
mbtiles4j = { group = "org.imintel", name = "mbtiles4j", version = "1.0.6" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version = "3.51.2.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version = "4.33.5" }
jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version = "3.0.0" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2-1" }
jts-core = { group = "org.locationtech.jts", name = "jts-core", version = "1.20.0" }
jts-io-common = { group = "org.locationtech.jts.io", name = "jts-io-common", version = "1.20.0" }
tileverse-io = { group = "io.tileverse", name = "tileverse-bom", version.ref = "tileverse" }
tileverse-rangereader-all = { module= "io.tileverse.rangereader:tileverse-rangereader-all" }
tileverse-pmtiles = { module = "io.tileverse.pmtiles:tileverse-pmtiles" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[plugins]
diffplug-spotless = { id = "com.diffplug.spotless", version = "8.2.1"}
gradleup-shadow = { id = "com.gradleup.shadow", version = "9.3.1"}