[versions]
tileverse = "1.3.3"
jmh = "1.37"
junit-jupiter = "6.0.3"
kotlin-jvm = "2.3.10"

[libraries]
commons-cli = { group = "commons-cli", name = "commons-cli", version = "1.11.0"}
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.28.0" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }
earcut4j = { group = "org.maplibre", name = "earcut4j", version = "3.0.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
guava = { group = "com.google.guava", name = "guava", version = "33.5.0-jre" }
hppc = { group = "com.carrotsearch", name = "hppc", version = "0.10.0" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.21.1" }
javaFastPFOR = { group = "me.lemire.integercompression", name = "JavaFastPFOR", version = "0.3.10" }
jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version = "3.0.0" }
java-vector-tile = { group = "no.ecc.vectortile", name = "java-vector-tile", version = "1.3.23" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "26.1.0" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh"}
jts-core = { group = "org.locationtech.jts", name = "jts-core", version = "1.20.0" }
jts-io-common = { group = "org.locationtech.jts.io", name = "jts-io-common", version = "1.20.0" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-jupiter"}
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-jvm" }
mapbox-vector-tile-java = { group = "io.github.sebasbaumh", name = "mapbox-vector-tile-java", version = "25.1.0" }
mbtiles4j = { group = "org.imintel", name = "mbtiles4j", version = "1.0.6" }
planetiler-core = { module= "com.onthegomap.planetiler:planetiler-core", version="0.10.0" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version = "4.34.0" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version = "2.25.3" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version = "2.25.3" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version = "3.51.2.0" }
tileverse-io = { group = "io.tileverse", name = "tileverse-bom", version.ref = "tileverse" }
tileverse-rangereader-all = { module= "io.tileverse.rangereader:tileverse-rangereader-all" }

[plugins]
diffplug-spotless = { id = "com.diffplug.spotless", version = "8.2.1"}
gradleup-shadow = { id = "com.gradleup.shadow", version = "9.3.1"}
me-champeau-jmh = { id = "me.champeau.jmh", version = "0.7.3" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
