name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'justfile'
      - '.github/**'
      - 'cpp/**'
      - 'test/**'

jobs:
  build:
    permissions:
      id-token: write  # for OIDC Codecov
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: cpp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }

      - name: Configure with CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug

      - name: Build the project
        run: cmake --build build --target mlt-cpp-test mlt-cpp-json

      - name: Run C++ tests
        run: cd build && ctest -T Test -T Coverage

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'maplibre'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          directory: cpp

      - name: sanity test for mlt-cpp-json tool
        run: build/tool/mlt-cpp-json ../test/expected/tag0x01/bing/4-12-6.mlt | jq .

      - name: Build with Bazel
        run: bazel build //cpp:mlt_cpp

      - run: cd .. && just -v assert-git-is-clean
