name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'justfile'
      - '.github/**'
      - 'cpp/**'
      - 'test/**'

jobs:
  cpp-build:
    permissions:
      id-token: write  # for OIDC Codecov
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: cpp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: 'cpp/.nvmrc'

      - name: install gcovr (macOS)
        if: runner.os == 'macOS'
        run: brew install gcovr

      - name: install gcovr (Linux)
        if: runner.os == 'Linux'
        run: pip3 install gcovr

      - name: Build, test and generate coverage report
        run: just cpp-coverage

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'maplibre'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          disable_file_fixes: true
          disable_search: true
          files: cpp/build/coverage.xml

      - name: sanity test for mlt-cpp-json tool
        run: build/tool/mlt-cpp-json ../test/expected/tag0x01/bing/4-12-6.mlt | jq .

      - name: Build with Bazel
        run: bazel build //cpp:mlt_cpp

      - run: cd .. && just -v assert-git-is-clean
