name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'justfile'
      - 'cpp.just'
      - '.github/**'
      - 'cpp/**'
      - 'test/**'

jobs:
  cpp-build:
    permissions:
      id-token: write  # for OIDC Codecov
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }

      - name: install gcovr (macOS)
        if: runner.os == 'macOS'
        run: brew install gcovr

      - name: install gcovr (Linux)
        if: runner.os == 'Linux'
        run: pip3 install gcovr

      - name: Build, test and generate coverage report
        run: just -v cpp::coverage

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'maplibre'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          disable_file_fixes: true
          disable_search: true
          files: cpp/build/coverage.xml

      - name: Sanity test for mlt-cpp-json tool
        run: just -v cpp::test-json

      - name: Build with Bazel
        run: just -v cpp::bazel-build

      - run: just -v assert-git-is-clean
