name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/**'
      - 'java/**'
      - 'test/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-java:
    permissions:
      id-token: write  # for OIDC Codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: ./.github/actions/mlt-setup-java
      - run: just -v env-info-java
      - if: matrix.os == 'ubuntu-latest'
        name: Lint Java code. If fails, run `just fmt-java` to reformat, and `just lint-java` to see issues locally
        run: just -v lint-java

      - run: ./gradlew jacocoTestReport
        working-directory: java

      - run: just -v test-java-cli

      - name: Test Maven local publishing
        run: cd java && ./gradlew publishMavenPublicationToMavenLocal

      - run: npm install
        working-directory: java/encoding-server
      - run: npm run lint
        working-directory: java/encoding-server
      - run: npm run checkstyle
        working-directory: java/encoding-server
      - run: just -v assert-git-is-clean

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'maplibre'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          directory: java
