name: Java - Release

on:
  push:
    tags:
      - 'java-v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }

      - name: Get version from tag
        id: get_version
        run: |
          version="$(just extract-version java ${{ github.ref_name }})"
          echo version="$version" >> "$GITHUB_ENV"

      - name: Make gradlew executable
        run: chmod +x ./java/gradlew

      - name: Publish to Maven Central
        working-directory: java
        run: ./gradlew publishToMavenCentral -Pversion=${{ env.version }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Build CLI tool
        working-directory: java
        run: ./gradlew cli
      - run: just -v assert-git-is-clean

      - name: Rename CLI artifacts
        run: |
          cp java/mlt-cli/build/libs/encode.jar mlt-encode.jar
          cp java/mlt-cli/build/libs/decode.jar mlt-decode.jar

      - name: Add CLI artifacts to GitHub release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          tag_name: java-v${{ env.version }}
          fail_on_unmatched_files: true
          name: java-v${{ env.version }}
          files: |
            mlt-encode.jar
            mlt-decode.jar
