name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'justfile'
      - 'java.just'
      - '.github/**'
      - 'java/**'
      - 'test/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-java:
    permissions:
      id-token: write  # for OIDC Codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }
      - uses: ./.github/actions/mlt-setup-java
      - run: just -v java::env-info
      - if: matrix.os == 'ubuntu-latest'
        name: Lint Java code. If fails, run `just java::fmt` to reformat, and `just java::lint` to see issues locally
        run: just -v java::lint

      - run: just -v java::test-coverage

      - run: just -v java::test-cli

      - name: Test Maven local publishing
        run: just -v java::test-publish

      - run: npm ci
        working-directory: java/encoding-server
      - run: npm run lint
        working-directory: java/encoding-server
      - run: npm run checkstyle
        working-directory: java/encoding-server
      - run: just -v assert-git-is-clean

      - name: Upload coverage to Codecov
        if: github.repository_owner == 'maplibre'
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          directory: java

      - name: Test synthetic MLT generation
        run: just -v java::ci-check-synthetic-mlts
