name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'js/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'js/package-lock.json'
      - name: Lint JS code. If fails, run `just fmt-js` to reformat, and `just lint-js` to see issues locally
        run: just lint-js
      - run: just test-js

  bench-js:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'js/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'js/package-lock.json'
      - name: Bench JS decoder
        run: just bench-js

  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Lint Java code. If fails, run `just fmt-java` to reformat, and `just lint-java` to see issues locally
        run: just lint-java

  test-java:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - run: just test-java
      - run: just test-java-cli

  # This final step is needed to mark the entire workflow as successful
  done:
    # Don't change this name - it is used by the merge protection rules
    name: CI Finished
    runs-on: ubuntu-latest
    # List of all the other jobs that must pass for this job to start
    needs: [ test-java, lint-java, test-js, bench-js ]
    steps:
      - name: Finished
        run: echo "CI finished successfully"
