name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: ./.github/actions/mlt-setup-node
      - name: Lint JS code. If fails, run `just fmt-js` to reformat, and `just lint-js` to see issues locally
        run: just -v lint-js
      - run: just -v test-js
      - run: just -v build-js
      - name: Codecov upload
        if: '!cancelled()'
        uses: codecov/codecov-action@v5
        with:
          files: ts/coverage/coverage-final.json

  bench-js:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: ./.github/actions/mlt-setup-node
      - name: Bench JS decoder
        run: just -v bench-js

  test-java:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: ./.github/actions/mlt-setup-java
      - run: just -v env-info-java
      - if: matrix.os == 'ubuntu-latest'
        name: Lint Java code. If fails, run `just fmt-java` to reformat, and `just lint-java` to see issues locally
        run: just -v lint-java
      - run: just -v test-java
      - run: just -v test-java-cli
      - name: Test Maven local publishing
        run: cd java && ./gradlew publishMavenPublicationToMavenLocal

      - run: npm install
        working-directory: java/encoding-server

      - run: npm run lint
        working-directory: java/encoding-server

      - run: npm run format
        working-directory: java/encoding-server

      - uses: infotroph/tree-is-clean@69d598a958e8cb8f3d0e3d52b5ebcd8684f2adc2 # v1.0.6
        with:
          check_untracked: true


  # This final step is needed to mark the entire workflow as successful
  done:
    # Don't change this name - it is used by the merge protection rules
    name: CI Finished
    runs-on: ubuntu-latest
    # List of all the other jobs that must pass for this job to start
    needs: [ test-java, test-js, bench-js ]
    steps:
      - name: Finished
        run: echo "CI finished successfully"
