name: TypeScript CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'justfile'
      - 'ts/mod.just'
      - '.github/**'
      - 'ts/**'
      - 'test/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with: { tool: 'just,cargo-binstall' }
      - uses: ./.github/actions/mlt-setup-node
      - name: Lint JS code. If fails, run `just ts::fmt` to reformat, and `just ts::lint` to see issues locally
        run: just -v ts::lint
      - run: just -v ts::test
      - run: just -v ts::build
      - name: Codecov upload
        if: "github.repository_owner == 'maplibre' && !cancelled()"
        uses: codecov/codecov-action@v5
        with:
          files: ts/coverage/coverage-final.json
      - run: just -v assert-git-is-clean
